### ISSUE TITLE
Weekly Log Zahi Mizrahi

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartParking#1]
# The Weekly Log
New for semester 2, a fresh new page with a different name.
This is meant to help in monitoring everyone's assignments in the projects and what they are currently involved with. 

Please use this as a weekly log from week 2 till the end of semester, both for you and me to see.
Log here *_past_* work that is finished, as well as *_current_* tasks you are doing.

Whenever possible, please include an issue number that you are working on, or that you have finished working on.
Best to use the bulleted list as a way to put things organized. 

**Have a great semester!**

**Comment by zahimizrahi** [comment]
## **Week 1** (20/3-26/3)

- Adding labels, milestone, wiki, readme.MD, pictures from the second project. Issue #10 is closed. 

- Preparing features & ideas for meeting in 26/3 

- Refactoring GUI (issue #16) - about ~70% of the classes was refactored and edited. There's still some minor changes left to do that I'll continue next week.

**Comment by zahimizrahi** [comment]
## **Week 2** (26/3-2/4)

- Refactoring GUI (issue #16) - all of the classes was refactored and edited. issue is closed. 

- Adding Icons to all buttons in the GUI (issue #12). issue is closed. 

- Integrating CodeCov to our project - issue #22. almost closed, there's still a permission of admin that we need. I will ask Tom about it tomorrow at the meeting. 

- Using @TomPalny's help and solving the bug of @shaysegal  in issue #23. issue is closed. 

- Writing wiki about labels in the project (issue #19). issue is closed.

**Comment by zahimizrahi** [comment]
# Week 3 (2/4 - 18/4) 

(There was Passover vacation in this week... 😆 )

- trying to integrade CodeCov to our project (issue #22), including organizing all the files in the project. Issue is closed. 

- Adding "coding standards" page to wiki (issue #27). Issue is closed. 

- fixing some bugs in Travis. 

- Setting the environment of Ionic in my computer and starting to learn about it.

**Comment by zahimizrahi** [comment]
# Week 4 (18/4 - 25/4) 

- Making the presentation for the meeting in 24/4. Issue #28 is closed.

- Fast-Learning JavaScript, TypeScript and refreshing my knowledge on HTML. 

- Working on basic demo of GUI - issue #32. I built new application for this and put homepage, page with list to other pages and login page. I will add more pages in the next weeks.

**Comment by zahimizrahi** [comment]
# Week 5 (25/4 - 4/5) 

- Learning about observables in Ionic.

- Continue working on basic demo of GUI - issue #32. Added register page and logout options, and 
 added menu bar of the map page. we're still planning how to show the navigation commands, I believe it will be added in the next few weeks. 

- Helped @DavidCohen55  and @Shahar-Y on their problem with setting the correct Ionic environment.

**Comment by zahimizrahi** [comment]
# Week 6 (5/5 - 12/5) 

Not much contribution this week  😿  😭 

- Making the map as homepage and fixed minor changes on map display (issue #32) 

- Using CSS & Sass on the demo (issue #32). 

issue #32 will be closed today, since it's not longer demo, it's working client side.

**Comment by zahimizrahi** [comment]
# Week 7 (13/5 - 20/5)
first vacation 🍹 

 # Week 8 (21/5 - 28/5)
(I took a week off on week 7) 
- Keep working on  GUI design work in SASS (#41). 

- Writing user manual (#49). Issue is closed. 

- Working on login and register typescript functionality (since it's missing). There isn't issue about that but it's connected to #43.

**Comment by zahimizrahi** [comment]
# Week 9 (29/5 - 9/6) 
 
- Fixed user manual #48

- Fixed install me 

- Participated the client game: made constructive feedback about SmartMarket and BugQuery. 

- fixed minor bugs and warnings before the client game (on some parts in the project that  wasn't written by me ).

- Made last changes in GUI due to our feedbacks from the client game. Also, made few changes in the CSS/SASS Design. closed issue #41. 

- Fixing maven build: it won't run all the tests in maven install, just in CI of the travis. also, configuring the main class to be the rest_test\application.java (the server). closed issue #54. 

- Disabling navigation if the user isn't logged in: worked on issue #49. issue is closed. 

- Made few changes on the design of ChoosingPage page, also made global and consistent design for buttons and background in ionic. working on issue #57.

**Comment by zahimizrahi** [comment]
# Week 10 (9/6 - 15/6) 
 
- helped on the design of the poster (issue #69). issue is closed. 

- adding searchbar with autocomplete  ( issue #61). issue is closed.

- fixing bug - the spinner in navigation page is freezing (issue #62). issue is closed. 

- changed GUI due to recommendations from the "customer game": mainly, changed the design of navigation page and map page. 

# Week 11 (16/6 - 23/6) 
second vacation 🍹

**Comment by zahimizrahi** [comment]
# Week 12 (24/6-1/7) 

- Fixed a few GUI problems: some of them was major, some of them was minor. all is detailed in issue #78. issue is closed.

- fixed bug with email validation (issue #82). issue is closed. 

- fixed major bug with pop-up alert of login (issue #79). issue is closed. 

- correct instruction on register page (issue #96). issue is closed.

- wrote new install me & updated read.me (issue #95). issue is closed.

- refactoring&coding standards of client folder (issue #100). issue is closed.

- adding last searches  gui (issue #101). there wasn't a service for this, so I implemented service too. issue is closed.

- hiding login/logout from menu (issue #97). it was solved by @Shahar-Y . issue is closed.

- fixing bug: pages re-constructed when we use the menu bar (issue #87) . issue is closed. 

- organized the backlog (issue #115). issue is closed.

**Comment by zahimizrahi** [comment]
# Week 13 (24/6-1/7) 

- Participated in "Finals" of the course. made few minor changes in the GUI and solved issues such as #139 and #129 and some more.
