### ISSUE TITLE
project throw exceptions when working on ubuntu

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#23]
exception we try to login to user (happen to me and @sefialbo ):
![image](https://cloud.githubusercontent.com/assets/15847157/24578933/8732322a-16f4-11e7-8480-e273727a724c.png)

and it's not the only problem - for me the music doesn't work , instead throws exception: 
![image](https://cloud.githubusercontent.com/assets/15847157/24579022/dd86b06e-16f5-11e7-89e7-f36fa4d357a9.png)
I looked it up and they said that ubuntu 16.04 doesn't support javafx 1.8
(http://stackoverflow.com/questions/38164044/javafx-media-player-on-ubuntu-16-04)

so i think that we need to reach a decision: try to fix it or declare that we doesn't support ubuntu...

**Comment by zahimizrahi** [comment]
I think that we need to declare we don't support Ubuntu. Most of the GUI part is based on javafx 1.8 features, so changing it requires a lot of work (unnecessary work if you ask me)

From the expections, it seems that it doesn't work because of the sounds @Shahar-Y  added to the GUI, it's probably one of the main features of javafx 1.8. We can decide to remove this functionality, but it doesn't assure that without music it will work on Ubuntu.

**Comment by yossigil** [comment]
:-1:

**Comment by TomPalny** [comment]
It says that the problem is with mp3 specifically, but works fine with WAV.

http://stackoverflow.com/a/38194263

Try converting the sound to wav and test.

בתודה,
תום

**Comment by shaysegal** [comment]
Now it's working , thanks guys 👍🏻
